[package]
name = "rust-dns"
version = "0.1.0"
authors = ["Aaron Riekenberg <aaron.riekenberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.2"
env_logger = "0.7"
futures = "0.3"
log = "0.4"
surf = "1.0"
trust-dns-proto = "0.8"
