[package]
name = "rust-dns"
version = "0.1.0"
authors = ["Aaron Riekenberg <aaron.riekenberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7"
futures = "0.3"
log = "0.4"
surf = "1.0"
tokio = { version = "0.2", features = ["full"] }
trust-dns-proto = "0.8"
