[package]
name = "rust-dns"
version = "0.1.0"
authors = ["Aaron Riekenberg <aaron.riekenberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "0.99.12"
env_logger = "0.7.1"
futures = "0.3.1"
log = "0.4.8"
surf = "1.0.3"
trust-dns-proto = "0.8.0"
